### ISSUE TITLE
esc_attr() incorrectly called on $extra

### ISSUE THREAD

**Issue by goblindegook** [log-oscon/google-docs-oembed#1]
`esc_attr()` exists to escape HTML property values only.  For example, in the lines below it will encode the quote characters in `allowfullscreen="true"`, mangling the string.

```
        return \apply_filters( 'oembed_google_docs', sprintf(
            '<iframe width="%s" height="%s" frameborder="0" src="%s" %s></iframe>',
            \esc_attr( $width ),
            \esc_attr( $height ),
            \esc_url( $base_url ),
            \esc_attr( $extra )
        ), $matches, $attr, $url, $rawattr );
```

Since we have control over what goes into `$extra`, there's no harm in printing it unescaped.

**Comment by s3rgiosan** [comment]
Removed https://github.com/log-oscon/google-docs-oembed/commit/219b4082f9ea42042cf2f474ab59d632121613c1
